version: "3"
services:
  api:
    build:
      context: .
      dockerfile: build/package/insgo/Dockerfile
      args:
        IMAGE_NAME: ${GO_IMAGE}
        APP_NAME: ${APP_NAME}
        SERVICE: insgo
        PORT: ${API_PORT}
    env_file:
      - ./.env
    volumes:
      - ./:/${APP_NAME}
    ports:
      - ${API_PORT}:${API_PORT}
    links:
      - ${DB_HOST}:${DB_HOST}
  mysqldb:
    image: ${DB_IMAGE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
